name: Deploy Vercel

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VITE_API_URL: https://apiportafolio.lionsoftgt.site/api/v1
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - run: npm run build
        env:
          VITE_API_URL: https://apiportafolio.lionsoftgt.site/api/v1
          VITE_TELEGRAM_BOT_TOKEN: ${{ secrets.VITE_TELEGRAM_BOT_TOKEN }}
          VITE_TELEGRAM_CHAT_ID: ${{ secrets.VITE_TELEGRAM_CHAT_ID }}
      - name: Pull Vercel project
        run: npx vercel pull --yes --environment=production --token="${{ secrets.VERCEL_TOKEN }}"
      - name: Build Vercel output
        run: npx vercel build --prod --token="${{ secrets.VERCEL_TOKEN }}"
        env:
          VITE_API_URL: https://apiportafolio.lionsoftgt.site/api/v1
          VITE_TELEGRAM_BOT_TOKEN: ${{ secrets.VITE_TELEGRAM_BOT_TOKEN }}
          VITE_TELEGRAM_CHAT_ID: ${{ secrets.VITE_TELEGRAM_CHAT_ID }}
      - name: Deploy
        run: npx vercel deploy --prebuilt --prod --token="${{ secrets.VERCEL_TOKEN }}" --yes
